import mongoose from "mongoose";

const WholesalerSchema = new mongoose.Schema({
  businessName: { type: String, required: true },
  contactPerson: String,
  whatsappNumber: { type: String, required: true },
  
  // NEW: A detailed description for Gemini to understand the business context
  // e.g., "Custom manufacturer of sustainable bamboo textiles and sportswear"
  description: { type: String, required: true },

  // NEW: This stores the vector generated by Gemini text-embedding-004
  // It allows matching "Bamboo shirts" to "Sustainable Apparel"
  embedding: { 
    type: [Number], 
    required: true,
    index: true // Important for performance
  },

  categories: [{ type: String }], 
  tags: [{ type: String }],
  isVerified: { type: Boolean, default: false },
  rating: { type: Number, default: 5 },
  location: {
    country: String,
    city: String
  },

  // NEW: Tracks if the wholesaler is active and ready for leads
  status: { type: String, enum: ['active', 'paused', 'busy'], default: 'active' },
  
  createdAt: { type: Date, default: Date.now }
});

export default mongoose.model("wholesaler", WholesalerSchema);

